### ISSUE TITLE
Two tab improvements

### ISSUE THREAD

**Issue by knicholson32** [npnicholson/Micro#20]
### First
When opening a new tab, the new tab should be placed to the right of the currently selected tab.

### Second
When your mouse is over the tab bar, the size and pos of the tabs should be frozen. After the mouse leaves, animate the changes. Makes it easier to close lots of tabs.

**Comment by npnicholson** [comment]
The first task is done. New tabs now appear to the right of the currently selected tab, if there is one. Closing an active tab selects the tab to the left. Handles cases where there are no tabs when adding, and when there are no tabs after a removal.
